import { useCallback, useEffect, useMemo, useState } from 'react'
import { Check, RefreshCw, ShieldCheck, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import '../download-access.css'

type RequestRow={id:string;requester_id:string;resource_type:string;resource_key:string;resource_name:string;reason:string|null;status:'pending'|'approved'|'denied'|'revoked';requested_at:string;reviewed_at:string|null;reviewed_by:string|null;decision_note:string|null;grant_expires_at:string|null;download_count:number;last_downloaded_at:string|null}
type Person={id:string;full_name:string;email:string;department:string|null;job_title:string|null}

export default function AdminDownloadAccessManager(){
  const [rows,setRows]=useState<RequestRow[]>([]),[people,setPeople]=useState<Record<string,Person>>({}),[filter,setFilter]=useState<'pending'|'approved'|'all'>('pending'),[loading,setLoading]=useState(true),[notice,setNotice]=useState('')
  const load=useCallback(async()=>{if(!supabase)return;setLoading(true);const {data,error}=await supabase.from('workspace_download_requests').select('*').order('requested_at',{ascending:false}).limit(200);if(error){setNotice(error.message);setLoading(false);return}const requestRows=(data||[]) as RequestRow[];setRows(requestRows);const ids=[...new Set(requestRows.map(r=>r.requester_id))];if(ids.length){const {data:p}=await supabase.from('employee_profiles').select('id,full_name,email,department,job_title').in('id',ids);const map:Record<string,Person>={};for(const person of (p||[]) as Person[])map[person.id]=person;setPeople(map)}setLoading(false)},[])
  useEffect(()=>{void load()},[load])
  const shown=useMemo(()=>filter==='all'?rows:rows.filter(r=>r.status===filter),[rows,filter])
  const decide=async(row:RequestRow,decision:'approved'|'denied'|'revoked',hours=24)=>{if(!supabase)return;const note=decision==='denied'?window.prompt('Reason for denying this request?')||'Denied by administrator.':decision==='revoked'?window.prompt('Reason for revoking access?')||'Access revoked by administrator.':null;const expires=decision==='approved'?new Date(Date.now()+hours*3600000).toISOString():null;const {error}=await supabase.rpc('review_workspace_download_request',{p_request_id:row.id,p_decision:decision,p_decision_note:note,p_grant_expires_at:expires});if(error)setNotice(error.message);else{setNotice(decision==='approved'?`Access approved for ${hours} hours.`:`Request ${decision}.`);await load()}}
  return <section className="downloadAdmin glassCard">
    <div className="downloadAdminHeader"><div><span className="eyebrow">DOWNLOAD GOVERNANCE</span><h3>Download access approvals</h3><p>Every protected file download is requested, approved, time-bounded and auditable.</p></div><button className="glassButton" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></div>
    <div className="downloadAdminFilters">{(['pending','approved','all'] as const).map(v=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v}</button>)}</div>
    {notice&&<div className="moduleNotice">{notice}</div>}
    {loading?<div className="downloadRequestEmpty">Loading download requests…</div>:<div className="downloadRequestList">{shown.map(row=>{const person=people[row.requester_id];return <article className="downloadRequestCard" key={row.id}><div className="downloadRequestTop"><div className="downloadRequestIdentity"><strong>{row.resource_name}</strong><span>{person?.full_name||person?.email||row.requester_id}</span><small>{[person?.job_title,person?.department,row.resource_type].filter(Boolean).join(' · ')}</small></div><span className="downloadRequestBadge">{row.status}</span></div>{row.reason&&<p className="downloadRequestReason">{row.reason}</p>}<div className="downloadRequestMeta"><span>Requested {new Date(row.requested_at).toLocaleString()}</span>{row.grant_expires_at&&<span>Expires {new Date(row.grant_expires_at).toLocaleString()}</span>}<span>{row.download_count||0} downloads</span></div><div className="downloadRequestActions">{row.status==='pending'&&<><button className="primaryButton" onClick={()=>void decide(row,'approved',24)}><Check size={15}/>Approve 24h</button><button className="glassButton" onClick={()=>void decide(row,'approved',168)}><ShieldCheck size={15}/>Approve 7d</button><button className="glassButton danger" onClick={()=>void decide(row,'denied')}><X size={15}/>Deny</button></>}{row.status==='approved'&&<button className="glassButton danger" onClick={()=>void decide(row,'revoked')}><X size={15}/>Revoke</button>}</div></article>})}{shown.length===0&&<div className="downloadRequestEmpty">No download requests in this view.</div>}</div>}
  </section>
}
