import { useEffect, useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { BarChart3, BookOpenCheck, Building2, CalendarClock, CheckCircle2, CircleDollarSign, Handshake, Landmark, Megaphone, Percent, PieChart, ReceiptText, RefreshCw, Search, Target, TrendingUp, Users, WalletCards } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Field={key:string;label:string;type?:'text'|'number'|'date'|'select'|'textarea';required?:boolean;options?:string[]}
type Column={key:string;label:string;render?:(row:Record<string,unknown>)=>ReactNode}
const money=(v:unknown)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(v||0))
const dateFmt=(v:unknown)=>v?new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(String(v))):'—'

export function DataWorkbench({table,title,description,fields,columns,createLabel='Add record',orderBy='created_at'}:{table:string;title:string;description:string;fields:Field[];columns:Column[];createLabel?:string;orderBy?:string}){
 const [rows,setRows]=useState<Record<string,unknown>[]>([]),[form,setForm]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[query,setQuery]=useState('')
 const load=async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError('');const {data,error}=await supabase.from(table).select('*').order(orderBy,{ascending:false}).limit(100);if(error)setError(error.message);setRows((data||[]) as Record<string,unknown>[]);setLoading(false)}
 useEffect(()=>{void load()},[table])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q))):rows},[rows,query])
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setError('');const payload:Record<string,unknown>={};for(const f of fields){const v=form[f.key];if(v!==undefined&&v!=='')payload[f.key]=f.type==='number'?Number(v):v}const {error}=await supabase.from(table).insert(payload);setSaving(false);if(error){setError(error.message);return}setForm({});setOpen(false);await load()}
 return <div className="glassCard workbench"><div className="workbenchHead"><div><h3>{title}</h3><p>{description}</p></div><div className="workbenchActions"><button className="iconButton" onClick={()=>void load()} title="Refresh"><RefreshCw size={16}/></button><button className="primaryButton" onClick={()=>setOpen(v=>!v)}>{open?'Close':createLabel}</button></div></div><div className="moduleSearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}`}/></div>{error&&<div className="moduleError">{error}</div>}{open&&<form className="quickForm" onSubmit={submit}><div className="quickFormGrid">{fields.map(f=><label key={f.key}>{f.label}{f.type==='select'?<select required={f.required} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Select</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea required={f.required} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input required={f.required} type={f.type||'text'} value={form[f.key]||''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div><button className="primaryButton" disabled={saving}>{saving?'Saving...':'Save record'}</button></form>}<div className="moduleTableWrap"><table className="moduleTable"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={columns.length}>Loading…</td></tr>:visible.length===0?<tr><td colSpan={columns.length}>No records yet.</td></tr>:visible.map((r,i)=><tr key={String(r.id||i)}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):String(r[c.key]??'—')}</td>)}</tr>)}</tbody></table></div></div>
}
function Title({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="sectionTitle"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{subtitle}</p></div></div>}
function KPI({icon,label,value,hint}:{icon:ReactNode;label:string;value:string;hint:string}){return <div className="metric glassCard"><div className="metricIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div>}
function Tabs({items,active,onChange}:{items:string[];active:string;onChange:(v:string)=>void}){return <div className="moduleTabs">{items.map(i=><button key={i} className={i===active?'active':''} onClick={()=>onChange(i)}>{i}</button>)}</div>}

export function FinanceModule(){const [tab,setTab]=useState('Dashboard');const tabs=['Dashboard','Invoices','Bills','Expenses','Journals','Budgets','Assets','Tax & Close'];return <section><Title eyebrow="FINANCE & ACCOUNTING" title="Finance Control Centre" subtitle="Receivables, payables, journals, expenses, budgets, assets, tax and period close under finance-grade controls."/><div className="stats"><KPI icon={<CircleDollarSign/>} label="Revenue control" value="AR" hint="Invoices, balances and aging"/><KPI icon={<ReceiptText/>} label="Payables" value="AP" hint="Bills, approvals and due dates"/><KPI icon={<WalletCards/>} label="Spend control" value="OPEX" hint="Expenses and reimbursements"/><KPI icon={<PieChart/>} label="Planning" value="Budget" hint="Budgets and variance readiness"/></div><Tabs items={tabs} active={tab} onChange={setTab}/>
{tab==='Dashboard'&&<div className="grid3"><Feature icon={<Landmark/>} title="Cash & banking" text="Bank accounts, settlement records and reconciliation readiness."/><Feature icon={<BookOpenCheck/>} title="General ledger" text="Chart of accounts, journals and double-entry lines."/><Feature icon={<BarChart3/>} title="Reporting" text="Trial balance, P&L, balance sheet, cash flow and aging-ready data."/><Feature icon={<Percent/>} title="Tax" text="VAT, WHT and statutory obligations with due-date control."/><Feature icon={<CheckCircle2/>} title="Close" text="Month-end tasks, ownership and completion status."/><Feature icon={<CircleDollarSign/>} title="Ride economics" text="Booking revenue, refunds, corporate AR and partner/driver settlement support."/></div>}
{tab==='Invoices'&&<DataWorkbench table="finance_invoices" title="Customer invoices" description="Corporate and partner receivables." createLabel="New invoice" fields={[{key:'invoice_number',label:'Invoice number',required:true},{key:'customer_name',label:'Customer',required:true},{key:'issue_date',label:'Issue date',type:'date',required:true},{key:'due_date',label:'Due date',type:'date',required:true},{key:'total_amount',label:'Amount (NGN)',type:'number',required:true},{key:'status',label:'Status',type:'select',options:['draft','sent','part_paid','paid','overdue','void'],required:true}]} columns={[{key:'invoice_number',label:'Invoice'},{key:'customer_name',label:'Customer'},{key:'due_date',label:'Due',render:r=>dateFmt(r.due_date)},{key:'total_amount',label:'Total',render:r=>money(r.total_amount)},{key:'balance_due',label:'Balance',render:r=>money(r.balance_due)},{key:'status',label:'Status'}]}/>} 
{tab==='Bills'&&<DataWorkbench table="finance_bills" title="Vendor bills" description="Vendor and operating obligations." createLabel="New bill" fields={[{key:'bill_number',label:'Bill number',required:true},{key:'vendor_name',label:'Vendor',required:true},{key:'bill_date',label:'Bill date',type:'date',required:true},{key:'due_date',label:'Due date',type:'date'},{key:'total_amount',label:'Amount (NGN)',type:'number',required:true},{key:'status',label:'Status',type:'select',options:['draft','pending_approval','approved','part_paid','paid','overdue','void'],required:true}]} columns={[{key:'bill_number',label:'Bill'},{key:'vendor_name',label:'Vendor'},{key:'due_date',label:'Due',render:r=>dateFmt(r.due_date)},{key:'total_amount',label:'Total',render:r=>money(r.total_amount)},{key:'balance_due',label:'Balance',render:r=>money(r.balance_due)},{key:'status',label:'Status'}]}/>} 
{tab==='Expenses'&&<DataWorkbench table="finance_expenses" title="Expenses" description="Operating spend and reimbursement workflow." createLabel="Record expense" fields={[{key:'description',label:'Description',required:true},{key:'category',label:'Category',required:true},{key:'expense_date',label:'Date',type:'date',required:true},{key:'amount',label:'Amount (NGN)',type:'number',required:true},{key:'payment_method',label:'Payment method'},{key:'status',label:'Status',type:'select',options:['draft','submitted','approved','rejected','paid'],required:true}]} columns={[{key:'expense_date',label:'Date',render:r=>dateFmt(r.expense_date)},{key:'description',label:'Description'},{key:'category',label:'Category'},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'status',label:'Status'}]}/>} 
{tab==='Journals'&&<DataWorkbench table="finance_journals" title="Journal register" description="Journal headers for controlled accounting entries." createLabel="New journal" fields={[{key:'journal_number',label:'Journal number',required:true},{key:'journal_date',label:'Journal date',type:'date',required:true},{key:'description',label:'Description',required:true},{key:'status',label:'Status',type:'select',options:['draft','posted','reversed'],required:true}]} columns={[{key:'journal_number',label:'Journal'},{key:'journal_date',label:'Date',render:r=>dateFmt(r.journal_date)},{key:'description',label:'Description'},{key:'status',label:'Status'}]}/>} 
{tab==='Budgets'&&<DataWorkbench table="finance_budgets" title="Budgets" description="Department and category budgets." createLabel="Add budget" fields={[{key:'name',label:'Budget name',required:true},{key:'fiscal_year',label:'Fiscal year',type:'number',required:true},{key:'department',label:'Department',required:true},{key:'category',label:'Category',required:true},{key:'amount',label:'Amount (NGN)',type:'number',required:true},{key:'status',label:'Status',type:'select',options:['draft','approved','closed'],required:true}]} columns={[{key:'name',label:'Budget'},{key:'fiscal_year',label:'Year'},{key:'department',label:'Department'},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'status',label:'Status'}]}/>} 
{tab==='Assets'&&<DataWorkbench table="finance_assets" title="Fixed assets" description="Asset register and useful-life control." createLabel="Register asset" fields={[{key:'asset_code',label:'Asset code',required:true},{key:'name',label:'Asset name',required:true},{key:'category',label:'Category',required:true},{key:'purchase_date',label:'Purchase date',type:'date'},{key:'cost',label:'Cost (NGN)',type:'number',required:true},{key:'status',label:'Status',type:'select',options:['active','disposed','written_off'],required:true}]} columns={[{key:'asset_code',label:'Code'},{key:'name',label:'Asset'},{key:'category',label:'Category'},{key:'cost',label:'Cost',render:r=>money(r.cost)},{key:'status',label:'Status'}]}/>} 
{tab==='Tax & Close'&&<div className="grid2"><DataWorkbench table="finance_tax_obligations" title="Tax obligations" description="VAT, WHT and filing control." createLabel="Add obligation" fields={[{key:'tax_type',label:'Tax type',required:true},{key:'period_label',label:'Period',required:true},{key:'due_date',label:'Due date',type:'date',required:true},{key:'amount',label:'Amount (NGN)',type:'number'},{key:'status',label:'Status',type:'select',options:['open','prepared','filed','paid','overdue'],required:true}]} columns={[{key:'tax_type',label:'Tax'},{key:'period_label',label:'Period'},{key:'due_date',label:'Due',render:r=>dateFmt(r.due_date)},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'status',label:'Status'}]}/><DataWorkbench table="finance_close_tasks" title="Period close" description="Month-end and year-end checklist." createLabel="Add close task" fields={[{key:'period_label',label:'Period',required:true},{key:'task_name',label:'Task',required:true},{key:'due_date',label:'Due date',type:'date'},{key:'status',label:'Status',type:'select',options:['open','in_progress','review','complete'],required:true}]} columns={[{key:'period_label',label:'Period'},{key:'task_name',label:'Task'},{key:'due_date',label:'Due',render:r=>dateFmt(r.due_date)},{key:'status',label:'Status'}]}/></div>}</section>}

export function MarketingModule(){const [tab,setTab]=useState('Campaigns');const tabs=['Campaigns','Content','Attribution','Experiments','Assets'];return <section><Title eyebrow="MARKETING" title="Growth & Brand Command Centre" subtitle="Campaign planning, content governance, attribution, experimentation and creative asset control."/><div className="stats"><KPI icon={<Megaphone/>} label="Campaigns" value="Plan → Learn" hint="Objective, spend and outcome"/><KPI icon={<Target/>} label="Attribution" value="UTM" hint="Source and campaign visibility"/><KPI icon={<TrendingUp/>} label="Growth" value="CAC → LTV" hint="Acquisition economics"/><KPI icon={<CalendarClock/>} label="Content" value="Calendar" hint="Review and publishing"/></div><Tabs items={tabs} active={tab} onChange={setTab}/>
{tab==='Campaigns'&&<DataWorkbench table="marketing_campaigns" title="Campaigns" description="Objectives, channels, budgets and status." createLabel="New campaign" fields={[{key:'name',label:'Campaign name',required:true},{key:'objective',label:'Objective',required:true},{key:'channel',label:'Channel',required:true},{key:'start_date',label:'Start date',type:'date'},{key:'end_date',label:'End date',type:'date'},{key:'budget',label:'Budget (NGN)',type:'number'},{key:'status',label:'Status',type:'select',options:['draft','planned','live','paused','completed','cancelled'],required:true}]} columns={[{key:'name',label:'Campaign'},{key:'objective',label:'Objective'},{key:'channel',label:'Channel'},{key:'budget',label:'Budget',render:r=>money(r.budget)},{key:'status',label:'Status'}]}/>} 
{tab==='Content'&&<DataWorkbench table="marketing_content" title="Content calendar" description="Creative work from idea through publishing." createLabel="Add content" fields={[{key:'title',label:'Title',required:true},{key:'content_type',label:'Type',required:true},{key:'channel',label:'Channel',required:true},{key:'publish_at',label:'Publish date',type:'date'},{key:'status',label:'Status',type:'select',options:['idea','draft','review','approved','scheduled','published','archived'],required:true},{key:'copy_text',label:'Copy / brief',type:'textarea'}]} columns={[{key:'title',label:'Content'},{key:'content_type',label:'Type'},{key:'channel',label:'Channel'},{key:'publish_at',label:'Publish',render:r=>dateFmt(r.publish_at)},{key:'status',label:'Status'}]}/>} 
{tab==='Attribution'&&<DataWorkbench table="marketing_attribution" title="Attribution" description="Spend, leads, bookings and revenue by UTM source." createLabel="Add attribution" fields={[{key:'campaign_name',label:'Campaign',required:true},{key:'source',label:'Source',required:true},{key:'medium',label:'Medium',required:true},{key:'spend',label:'Spend (NGN)',type:'number'},{key:'leads',label:'Leads',type:'number'},{key:'bookings',label:'Bookings',type:'number'},{key:'revenue',label:'Revenue (NGN)',type:'number'}]} columns={[{key:'campaign_name',label:'Campaign'},{key:'source',label:'Source'},{key:'medium',label:'Medium'},{key:'spend',label:'Spend',render:r=>money(r.spend)},{key:'leads',label:'Leads'},{key:'bookings',label:'Bookings'},{key:'revenue',label:'Revenue',render:r=>money(r.revenue)}]}/>} 
{tab==='Experiments'&&<DataWorkbench table="marketing_experiments" title="Growth experiments" description="Hypotheses and measurable learning." createLabel="New experiment" fields={[{key:'name',label:'Experiment',required:true},{key:'hypothesis',label:'Hypothesis',type:'textarea',required:true},{key:'primary_metric',label:'Primary metric',required:true},{key:'start_date',label:'Start date',type:'date'},{key:'end_date',label:'End date',type:'date'},{key:'status',label:'Status',type:'select',options:['planned','running','won','lost','inconclusive'],required:true}]} columns={[{key:'name',label:'Experiment'},{key:'primary_metric',label:'Metric'},{key:'start_date',label:'Start',render:r=>dateFmt(r.start_date)},{key:'status',label:'Status'}]}/>} 
{tab==='Assets'&&<DataWorkbench table="marketing_assets" title="Creative assets" description="Approved brand and campaign assets." createLabel="Register asset" fields={[{key:'name',label:'Asset name',required:true},{key:'asset_type',label:'Type',required:true},{key:'channel',label:'Channel'},{key:'storage_path',label:'Path / URL'},{key:'status',label:'Status',type:'select',options:['draft','review','approved','retired'],required:true}]} columns={[{key:'name',label:'Asset'},{key:'asset_type',label:'Type'},{key:'channel',label:'Channel'},{key:'status',label:'Status'}]}/>}</section>}

export function PartnershipsModule(){const [tab,setTab]=useState('Partners');const tabs=['Partners','Pipeline','Agreements','Activities','Referrals','Onboarding'];return <section><Title eyebrow="PARTNERSHIPS" title="Partnerships & Alliances" subtitle="Prospecting, commercial pipeline, contracts, relationship history, referrals and launch readiness."/><div className="stats"><KPI icon={<Handshake/>} label="Lifecycle" value="End-to-end" hint="Prospect to renewal"/><KPI icon={<Building2/>} label="Segments" value="Multi-sector" hint="Hotels, travel, corporate and more"/><KPI icon={<CircleDollarSign/>} label="Commercial" value="Pipeline" hint="Value and commission"/><KPI icon={<Users/>} label="Relationships" value="360°" hint="Contacts and activity"/></div><Tabs items={tabs} active={tab} onChange={setTab}/>
{tab==='Partners'&&<DataWorkbench table="partners" title="Partner directory" description="Master partner relationship record." createLabel="New partner" fields={[{key:'name',label:'Partner name',required:true},{key:'partner_type',label:'Partner type',type:'select',options:['hotel','corporate','travel_agency','airline','tourism','embassy','institution','technology','other'],required:true},{key:'status',label:'Status',type:'select',options:['prospect','engaged','active','paused','inactive'],required:true},{key:'website',label:'Website'},{key:'city',label:'City'},{key:'notes',label:'Notes',type:'textarea'}]} columns={[{key:'name',label:'Partner'},{key:'partner_type',label:'Type'},{key:'city',label:'City'},{key:'status',label:'Status'}]}/>} 
{tab==='Pipeline'&&<DataWorkbench table="partner_opportunities" title="Partnership pipeline" description="Commercial opportunities and next actions." createLabel="New opportunity" fields={[{key:'opportunity_name',label:'Opportunity',required:true},{key:'partner_name',label:'Partner',required:true},{key:'stage',label:'Stage',type:'select',options:['identified','qualified','proposal','negotiation','due_diligence','contracting','won','lost'],required:true},{key:'estimated_value',label:'Estimated value (NGN)',type:'number'},{key:'expected_close_date',label:'Expected close',type:'date'},{key:'next_action',label:'Next action'}]} columns={[{key:'opportunity_name',label:'Opportunity'},{key:'partner_name',label:'Partner'},{key:'stage',label:'Stage'},{key:'estimated_value',label:'Value',render:r=>money(r.estimated_value)},{key:'expected_close_date',label:'Close',render:r=>dateFmt(r.expected_close_date)}]}/>} 
{tab==='Agreements'&&<DataWorkbench table="partner_agreements" title="Agreements" description="Rates, commissions, SLA and renewal governance." createLabel="New agreement" fields={[{key:'partner_name',label:'Partner',required:true},{key:'agreement_type',label:'Agreement type',required:true},{key:'effective_date',label:'Effective date',type:'date'},{key:'expiry_date',label:'Expiry date',type:'date'},{key:'commission_rate',label:'Commission %',type:'number'},{key:'status',label:'Status',type:'select',options:['draft','review','signed','active','expired','terminated'],required:true},{key:'document_path',label:'Document path / URL'}]} columns={[{key:'partner_name',label:'Partner'},{key:'agreement_type',label:'Agreement'},{key:'expiry_date',label:'Expiry',render:r=>dateFmt(r.expiry_date)},{key:'commission_rate',label:'Commission %'},{key:'status',label:'Status'}]}/>} 
{tab==='Activities'&&<DataWorkbench table="partner_activities" title="Relationship activities" description="Meetings, calls and follow-ups." createLabel="Log activity" fields={[{key:'partner_name',label:'Partner',required:true},{key:'activity_type',label:'Type',type:'select',options:['meeting','call','email','proposal','review','task'],required:true},{key:'subject',label:'Subject',required:true},{key:'activity_date',label:'Date',type:'date',required:true},{key:'next_action',label:'Next action'},{key:'notes',label:'Notes',type:'textarea'}]} columns={[{key:'activity_date',label:'Date',render:r=>dateFmt(r.activity_date)},{key:'partner_name',label:'Partner'},{key:'activity_type',label:'Type'},{key:'subject',label:'Subject'},{key:'next_action',label:'Next action'}]}/>} 
{tab==='Referrals'&&<DataWorkbench table="partner_referrals" title="Partner referrals" description="Booking attribution and commission obligations." createLabel="Add referral" fields={[{key:'partner_name',label:'Partner',required:true},{key:'booking_reference',label:'Booking reference',required:true},{key:'customer_name',label:'Customer'},{key:'booking_value',label:'Booking value (NGN)',type:'number'},{key:'commission_amount',label:'Commission (NGN)',type:'number'},{key:'status',label:'Status',type:'select',options:['pending','confirmed','payable','paid','cancelled'],required:true}]} columns={[{key:'booking_reference',label:'Booking'},{key:'partner_name',label:'Partner'},{key:'booking_value',label:'Value',render:r=>money(r.booking_value)},{key:'commission_amount',label:'Commission',render:r=>money(r.commission_amount)},{key:'status',label:'Status'}]}/>} 
{tab==='Onboarding'&&<DataWorkbench table="partner_onboarding_tasks" title="Partner onboarding" description="Commercial, legal, finance, operations, technology and marketing launch tasks." createLabel="Add task" fields={[{key:'partner_name',label:'Partner',required:true},{key:'task_name',label:'Task',required:true},{key:'workstream',label:'Workstream',type:'select',options:['commercial','legal','finance','operations','technology','marketing'],required:true},{key:'due_date',label:'Due date',type:'date'},{key:'status',label:'Status',type:'select',options:['not_started','in_progress','blocked','complete'],required:true}]} columns={[{key:'partner_name',label:'Partner'},{key:'task_name',label:'Task'},{key:'workstream',label:'Workstream'},{key:'due_date',label:'Due',render:r=>dateFmt(r.due_date)},{key:'status',label:'Status'}]}/>}</section>}

function Feature({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="glassCard feature"><div className="iconBox">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
