import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { BadgeCheck, CalendarDays, FileCheck2, Headphones, Route, ShieldAlert, Users } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { DataWorkbench } from './BusinessModules'

function Title({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="sectionTitle"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{subtitle}</p></div></div>}

export function CRMModule(){return <section><Title eyebrow="CUSTOMER RELATIONSHIPS" title="CRM" subtitle="Live commercial pipeline and account management backed by Supabase."/><div className="grid2"><DataWorkbench table="crm_leads" title="Lead pipeline" description="Create and manage qualified demand." createLabel="New lead" fields={[{key:'name',label:'Name',required:true},{key:'company',label:'Company'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'source',label:'Source'},{key:'stage',label:'Stage',type:'select',options:['new','qualified','proposal','negotiation','won','lost'],required:true},{key:'estimated_value',label:'Estimated value (NGN)',type:'number'}]} columns={[{key:'name',label:'Lead'},{key:'company',label:'Company'},{key:'source',label:'Source'},{key:'stage',label:'Stage'},{key:'estimated_value',label:'Value'}]}/><DataWorkbench table="crm_accounts" title="Accounts" description="Riders, corporate, hotel and travel relationships." createLabel="New account" fields={[{key:'name',label:'Account name',required:true},{key:'account_type',label:'Type',type:'select',options:['individual','corporate','hotel','travel_partner','other'],required:true},{key:'lifecycle_stage',label:'Lifecycle',required:true},{key:'estimated_value',label:'Estimated value (NGN)',type:'number'},{key:'status',label:'Status',required:true}]} columns={[{key:'name',label:'Account'},{key:'account_type',label:'Type'},{key:'lifecycle_stage',label:'Lifecycle'},{key:'estimated_value',label:'Value'},{key:'status',label:'Status'}]}/></div></section>}

export function SupportModule(){return <section><Title eyebrow="SUPPORT CONTROL" title="Support Station" subtitle="Case intake, booking context, priority and resolution workflow."/><div className="grid2"><DataWorkbench table="support_cases" title="Support cases" description="Customer and booking issues from intake through closure." createLabel="New case" fields={[{key:'reference',label:'Reference',required:true},{key:'subject',label:'Subject',required:true},{key:'category',label:'Category',required:true},{key:'priority',label:'Priority',type:'select',options:['low','normal','high','critical'],required:true},{key:'status',label:'Status',type:'select',options:['open','in_progress','waiting','resolved','closed'],required:true},{key:'booking_reference',label:'Booking reference'}]} columns={[{key:'reference',label:'Reference'},{key:'subject',label:'Subject'},{key:'category',label:'Category'},{key:'priority',label:'Priority'},{key:'status',label:'Status'}]}/><div className="glassCard feature"><Headphones/><h3>Support operating standard</h3><p>Every case has a reference, category, priority and status. Critical safety events must also be logged as incidents.</p><div className="miniChecklist"><span><BadgeCheck size={15}/>Identity and booking verified</span><span><Route size={15}/>Trip context captured</span><span><ShieldAlert size={15}/>Safety escalation linked when required</span></div></div></div></section>}

export function OperationsModule(){return <section><Title eyebrow="OPERATIONS" title="Ride Operations" subtitle="Incident management and operational exception control."/><div className="grid2"><DataWorkbench table="incidents" title="Incident register" description="Safety, service and operational exceptions." createLabel="New incident" fields={[{key:'reference',label:'Reference',required:true},{key:'severity',label:'Severity',type:'select',options:['low','medium','high','critical'],required:true},{key:'category',label:'Category',required:true},{key:'summary',label:'Summary',type:'textarea',required:true},{key:'status',label:'Status',required:true}]} columns={[{key:'reference',label:'Reference'},{key:'severity',label:'Severity'},{key:'category',label:'Category'},{key:'summary',label:'Summary'},{key:'status',label:'Status'}]}/><div className="glassCard feature"><Route/><h3>Live operations integration</h3><p>Dispatch, driver readiness, fleet and live-trip data should be consumed from RideArrivo backend APIs rather than duplicated in this database.</p></div></div></section>}

export function LegalModule(){return <section><Title eyebrow="LEGAL & COMPLIANCE" title="Legal workspace" subtitle="Contracts, renewal dates, evidence and compliance control."/><div className="grid2"><DataWorkbench table="legal_contracts" title="Contract register" description="Counterparties, status and renewal dates." createLabel="New contract" fields={[{key:'title',label:'Contract title',required:true},{key:'counterparty',label:'Counterparty',required:true},{key:'status',label:'Status',required:true},{key:'effective_date',label:'Effective date',type:'date'},{key:'renewal_date',label:'Renewal date',type:'date'},{key:'document_path',label:'Document path / URL'}]} columns={[{key:'title',label:'Contract'},{key:'counterparty',label:'Counterparty'},{key:'status',label:'Status'},{key:'effective_date',label:'Effective'},{key:'renewal_date',label:'Renewal'}]}/><DataWorkbench table="compliance_items" title="Compliance register" description="Obligations, evidence and due dates." createLabel="Add compliance item" fields={[{key:'title',label:'Obligation',required:true},{key:'due_date',label:'Due date',type:'date'},{key:'status',label:'Status',required:true},{key:'evidence_path',label:'Evidence path / URL'}]} columns={[{key:'title',label:'Obligation'},{key:'due_date',label:'Due date'},{key:'status',label:'Status'},{key:'evidence_path',label:'Evidence'}]}/></div></section>}

export function PeopleModule(){const [employees,setEmployees]=useState<Record<string,unknown>[]>([]),[leave,setLeave]=useState({leave_type:'Annual',start_date:'',end_date:'',reason:''}),[message,setMessage]=useState('');useEffect(()=>{if(!supabase)return;void supabase.from('employee_profiles').select('id,full_name,email,department,job_title,role').order('full_name').then(({data})=>setEmployees((data||[]) as Record<string,unknown>[]))},[]);const submit=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage('Session expired.');return}const {error}=await supabase.from('leave_requests').insert({employee_id:user.id,...leave});setMessage(error?error.message:'Leave request submitted.');if(!error)setLeave({leave_type:'Annual',start_date:'',end_date:'',reason:''})};return <section><Title eyebrow="PEOPLE & HR" title="People Operations" subtitle="Employee directory and secure employee self-service."/><div className="grid2"><div className="glassCard workbench"><div className="workbenchHead"><div><h3>Employee directory</h3><p>Live company directory.</p></div><Users/></div><div className="moduleTableWrap"><table className="moduleTable"><thead><tr><th>Name</th><th>Department</th><th>Job title</th><th>Role</th></tr></thead><tbody>{employees.map(e=><tr key={String(e.id)}><td>{String(e.full_name||e.email)}</td><td>{String(e.department||'—')}</td><td>{String(e.job_title||'—')}</td><td>{String(e.role||'employee')}</td></tr>)}</tbody></table></div></div><div className="glassCard workbench"><div className="workbenchHead"><div><h3>Request leave</h3><p>Employee self-service protected by RLS.</p></div><CalendarDays/></div><form className="quickForm" onSubmit={submit}><div className="quickFormGrid"><label>Leave type<select value={leave.leave_type} onChange={e=>setLeave({...leave,leave_type:e.target.value})}><option>Annual</option><option>Sick</option><option>Compassionate</option><option>Study</option><option>Unpaid</option></select></label><label>Start date<input type="date" required value={leave.start_date} onChange={e=>setLeave({...leave,start_date:e.target.value})}/></label><label>End date<input type="date" required value={leave.end_date} onChange={e=>setLeave({...leave,end_date:e.target.value})}/></label><label>Reason<textarea value={leave.reason} onChange={e=>setLeave({...leave,reason:e.target.value})}/></label></div>{message&&<div className="moduleNotice">{message}</div>}<button className="primaryButton">Submit request</button></form></div></div></section>}

export function AdminModule(){return <section><Title eyebrow="ADMINISTRATION" title="Workspace administration" subtitle="Application registry and security controls. Admin mutations are enforced by RLS."/><div className="grid2"><DataWorkbench table="workspace_apps" title="Application registry" description="Native, API and embedded workspace applications." createLabel="Register app" fields={[{key:'name',label:'Name',required:true},{key:'slug',label:'Slug',required:true},{key:'url',label:'URL'},{key:'mode',label:'Mode',type:'select',options:['native','embed','api','download'],required:true}]} columns={[{key:'name',label:'Application'},{key:'slug',label:'Slug'},{key:'mode',label:'Mode'},{key:'url',label:'URL'}]}/><div className="glassCard feature"><FileCheck2/><h3>Security posture</h3><p>Role access is enforced at Supabase RLS. Service-role keys must never be exposed in Vite or Cloudflare frontend variables.</p><div className="miniChecklist"><span><BadgeCheck size={15}/>RideArrivo-only email authentication</span><span><BadgeCheck size={15}/>RLS on business tables</span><span><BadgeCheck size={15}/>Anon table access revoked</span></div></div></div></section>}
